Lesson3
00agata/PythonLearning pull request #10
Opened 2018-03-22 18:16 UTC by 00agata

Please, add to master branch. It works well in PyCharm (Python 2.7)

2018-04-11 14:58 UTC, jedzej requested changes
Wrzuciłaś część zadań w folderze AtBS. Tak ma być? Co to za akronim? :)

2018-04-11 14:58 UTC, jedzej commented on AtBS/TheCollatzSequence.py
> +def collatz(number):
zgodnie z poleceniem funkcja collatz ma printować i zwracać, tutaj tylko zwraca

2018-04-11 14:58 UTC, jedzej commented on AtBS/calculator.py
> +        add_var_1 = int(input("Input 1st operand:"))
czytanie operandów powinno być wyizolowane do osobnej funckji, żeby uniknąć powtarzania kodu

2018-04-11 14:58 UTC, jedzej commented on Chapter8/Zad1The_length_of_the_segment.py
> +    distance_square = ((x_2-x_1)**2 + (y_2-y_1)**2)
zewnętrzny nawias jest zbędny

2018-04-11 14:58 UTC, jedzej commented on Chapter8/Zad2Negative_exponent.py
> +def power(a, n):
tu chodzi o to, żeby użyć power z zadania z eksponentą, wtedy będzie większe zmóżdżenie, bo negative exponent nie będzie działać od strzała

2018-04-11 14:58 UTC, jedzej commented on Chapter8/Zad6Fibonacci_numbers.py
> +    a.append(a2)
Do tego zadania można podejść na dwa sposoby:

1. wykorzystać rekurencję (taki był zamysł)
2. wykorzystać pętlę (wtedy będzie bardziej skompliowany kod, ale rozwiązanie jest bardziej wydajne obliczeniowo)

W obu z tych sposobów lista jest zbędna

2018-05-03 18:25 UTC, 00agata commented
AtBS - Automate the Boring Stuff (with Python)

2018-06-03 22:38 UTC, jedzej approved these changes

2018-06-03 22:38 UTC, merged