Lesson7
00agata/PythonLearning pull request #14
Opened 2018-06-11 20:34 UTC by 00agata

Please add to master

2018-07-08 16:25 UTC, jedzej requested changes
plz fix

2018-07-08 16:25 UTC, jedzej commented on Lesson7/DateCalculator.py
> +def calculate_date(yr, days, hr, min):
zmienna `min` przesłania globalną funkcję `min`

2018-07-08 16:25 UTC, jedzej commented on Lesson7/DateCalculator.py
> +def calculate_date(yr, days, hr, min):
zmienna `days` jest nieużywana

2018-07-08 16:25 UTC, jedzej commented on Lesson7/DateCalculator.py
> +    if yr % 4 == 0:
wydaje mi się, że to nie jest poprawne podejście przy dodawaniu lat, bo jeżeli do 2007 roku dodasz 2 lata to przekroczysz rok przestępny, co nie zostanie wychwycone w tym algorytmie

Raczej należy zastosować `timedelta` do takich operacji zamiast robić na piechotę https://docs.python.org/3/library/datetime.html#datetime.timedelta

2018-07-08 16:25 UTC, jedzej commented on Lesson7/DatePrinter
> +'''
plik bez rozszerzenia?

2018-07-08 16:25 UTC, jedzej commented on Lesson7/DatePrinter
> +import datetime
importy powinny być na początku pliku

2018-07-08 16:25 UTC, jedzej commented on Lesson7/DeltaTimeCalculator.py
> +    # print(delta_total_seconds)
niepotrzebne komentarze usuwamy

2018-07-08 16:25 UTC, jedzej commented on Lesson7/DeltaTimeCalculator.py
> +    second = (int(custom_time[2]))
jakoś sobie poradziłaś na piechotę, ale jest gotowiec na parsowanie daty:

https://docs.python.org/3/library/datetime.html#datetime.datetime.strptime

2018-07-08 16:25 UTC, jedzej commented on Lesson7/TimestampToDate.py
> +# complete
bardzo dużo komentarzy niepotrzebnych

2018-07-08 16:25 UTC, jedzej commented on Lesson7/ToSwapTheTwoWords.py
> +    str = ' '.join(list_str_2)
przesłonięcie wbudowanej funkcji `str`

2018-07-08 16:25 UTC, jedzej commented on Lesson7/TablePrinter.py
> +    rowAmount = []
skąd taki Javaizm? :) PEP8 zaleca nazywanie `row_amount`

2018-07-08 16:25 UTC, jedzej commented on Lesson7/ReplaceTheSubstring.py
> +def replace_substring(substring, sampleString, replacement):
tutaj też camelCase zamiast snake_case

2018-07-09 20:59 UTC, 00agata commented on Lesson7/DeltaTimeCalculator.py
> +    second = (int(custom_time[2]))
To nie działa: datetime(*(time.strptime(custom_date, format)[0:6]))

Zwraca mi błąd: TypeError: strptime() argument 1 must be str, not <class 'builtin_function_or_method'>

Nie wiem o co mu chodzi, ponieważ custom_date jest właśnie stringiem:

custom_date = str(input('Provide custom date in following '
                        'format: 2018.06.10 18:26:19  '))

Jak widać jest str(input(...

czyli string.

2018-10-28 16:49 UTC, jedzej reviewed
z tym datetime to dobrze ogarniać temat

2018-10-28 16:49 UTC, jedzej commented on Lesson7/DatePrinter.py
> +    return date
po co ta tablica?
poza tym te dwie metody opierają się na tym samym - printowanie prost obiektu date

2018-10-28 16:49 UTC, jedzej commented on Lesson7/DeltaTimeCalculator.py
> +    second = (int(custom_time[2]))
Coś tam namieszane jest. To nie działa?
```
datetime_obj = datetime.datetime.strptime(string_date,"%d.%m.%Y %H:%M:%S")
```

2018-11-12 14:29 UTC, closed without merging