zad3, please add to master branch
00agata/PythonLearning pull request #3
Opened 2018-01-28 14:02 UTC by 00agata

2018-01-28 14:09 UTC, jedzej commented on Chapter1/Zad3.py
> +            print ("Each student will receive %d apple" % apples_per_student)
lepiej formatować nową metodą .format

2018-01-28 14:09 UTC, jedzej commented on Chapter1/Zad3.py
> +apples_amount = 0
zamiast trzymać w globalu lepiej przekazać te wartości jako argumenty funkcji

2018-01-28 14:09 UTC, jedzej commented on Chapter1/Zad3.py
> +except ValueError:
bardzo dobrze, że obsługujesz wyjątek

2018-01-28 14:09 UTC, jedzej commented on Chapter1/Zad3.py
> +    students_amount = raw_input("How many students? Please, provide amount: ")
czemu raw_input? zwykły input nie sprawdza się tutaj?

2018-01-29 19:19 UTC, jedzej requested changes

2018-01-29 19:19 UTC, jedzej commented on Chapter1/Zad4.py
> +    integer_ = raw_input("Please, provide sample integer: ")
PEP zaleca nazywać zmienne małymi literami z kolejnymi wyrazami odseparowanymi underscorem, https://www.python.org/dev/peps/pep-0008/#function-and-variable-names nie rozumiem tego sufiksu

2018-01-29 19:19 UTC, jedzej commented on Chapter1/Zad4.py
> +    print ("Previous integer: {}").format(prev_integer_)
w pythonie2 nie ma potrzeby brać "Previous integer: {}" w nawiasy, a w pythonie3 będzie błąd, zgadnij dlaczego

2018-01-29 19:19 UTC, jedzej commented on Chapter1/Zad4.py
> +    print ("Next integer: {}").format(next_integer_)
tutaj też

2018-01-29 19:19 UTC, jedzej commented on Chapter1/Zad4_.py
> +if '.' in str(integer_):
sprytnie, ale jeżeli chcesz sprawdzić czy zmienna jest jakiegoś typu to lepszym pomysłem jest użycie funkcji isinstance lub type niż castowanie i szukanie kropek:)

2018-01-29 19:19 UTC, jedzej commented on Chapter1/Zad4.py
> +    integer_ = raw_input("Please, provide sample integer: ")
dodatkowo integer_ wcale nie jest na tym etapie intem tylko stringiem przez zastosowanie raw_input, więc nazwa jest trochę myląca

2018-01-29 19:19 UTC, jedzej commented on Chapter1/Zad4_.py
> +    print ("Previous integer: {}").format(prev_integer_)
to samo co w zad4

2018-01-29 19:19 UTC, jedzej commented on Chapter1/Zad5.py
> +'''
A school decided to replace the desks in three classrooms. Each desk sits two students. Given the number of students in each class, print the smallest possible number of desks that can be purchased.
The program should read three integers: the number of students in each of the three classes, a, b and c respectively.

In the first test there are three groups. The first group has 20 students and thus needs 10 desks. The second group has 21 students, so they can get by with no fewer than 11 desks. 11 desks is also enough for the third group of 22 students. So we need 32 desks in total.

2018-01-29 19:59 UTC, jedzej requested changes

2018-01-29 19:59 UTC, jedzej commented on Chapter1/Zad5.py
> +    temp = students_amount % table_students
unikaj nazw takich jak "temp", bo to nic nie mówi, całe działanie modulo można wrzucić do ifa

2018-01-29 19:59 UTC, jedzej commented on Chapter1/Zad5.py
> +        tables_amount = (students_amount // table_students) + 1
nawias nie jest błędem, ale jest zbędny, najpierw wykona się dzielenie

2018-01-29 19:59 UTC, jedzej commented on Chapter1/Zad5.py
> +def count_tables_amount (students_amount):
to się da zrobić w 1 linijce, wiesz jak?

2018-01-29 19:59 UTC, jedzej commented on Chapter1/Zad5.py
> +    students_a = raw_input("Please, provide amount of students in class a: ")
jak użyjesz input zamiast raw_input to nie będziesz musiała rzutować

2018-01-29 19:59 UTC, jedzej commented on Chapter1/Zad5.py
> +students = {}
tutaj bardziej pasowałaby lista niż dict, bo nie ma potrzeby żeby rozróżniać klasy wg kluczy, ale to jest wybieganie z materiałem

2018-01-29 19:59 UTC, jedzej commented on Chapter1/Zad5.py
> +    students_a = raw_input("Please, provide amount of students in class a: ")
możesz przypisać raw_input bezpośrednio do students['students_A'], nie ma potrzeby tworzenia dodatkowej zmiennej

2018-01-29 19:59 UTC, jedzej commented on Chapter1/Zad5.py
> +
PEP zaleca, żeby ostatnia linia była pusta, tu są spacje

2018-01-29 19:59 UTC, jedzej commented on Chapter1/Zad5.py
> +    for students_ in students:
dziwna ta konwencja z sufiksem '_'
interesują Cię tylko wartości ze słownika, jest do tego metoda values(), która zwraca listę wartości

2018-02-20 17:57 UTC, jedzej requested changes
usuń plik chapter2/zad1.py

2018-02-27 19:47 UTC, jedzej requested changes

2018-02-27 19:47 UTC, jedzej commented on Chapter1/Zad5.py
> +    return students_amount // 2 + 1
nie przechodzi najprostszego testu - dla parzystej liczby uczniów będzie o 1 ławkę za dużo

2018-02-28 15:30 UTC, 00agata commented on Chapter1/Zad3.py
> +    students_amount = raw_input("How many students? Please, provide amount: ")
Może być input i od razu rzutowanie na iint

2018-02-28 15:34 UTC, 00agata commented on Chapter1/Zad5.py
> +    for students_ in students:
Ja tu robię przypisanie wartości do klucza, więc jak mam użyć tej funkcji?

2018-03-02 10:40 UTC, jedzej approved these changes

2018-03-02 10:40 UTC, merged